# Generated by Django 5.0.7 on 2024-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='explanation',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
