# Generated by Django 5.0.7 on 2024-08-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0002_ipaddress_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='explanation',
            new_name='aciklama',
        ),
    ]
