# Generated by Django 5.0.7 on 2024-08-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0003_rename_explanation_ipaddress_aciklama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='aciklama',
            new_name='açıklama',
        ),
    ]
